-- 008_roles_permissions.sql
-- Seeds the 13 system roles, every permission the Flutter client can check
-- (extracted from lib/core/constants/permission_constants.dart) and the
-- default role -> permission matrix.

insert into public.roles (name, description, is_system_role) values
  ('SUPER ADMIN',      'Unrestricted access to every showroom and module.', true),
  ('ADMIN',            'Full access within the assigned showroom.', true),
  ('SHOWROOM MANAGER', 'Runs day-to-day showroom operations.', true),
  ('ACCOUNT MANAGER',  'Owns accounting, payments and finance.', true),
  ('SALES MANAGER',    'Owns sales, billing and customer relationships.', true),
  ('SALES STAFF',      'Sells bikes and records customer payments.', true),
  ('SERVICE MANAGER',  'Owns the workshop, warranty and free services.', true),
  ('SERVICE ADVISOR',  'Opens and closes job cards.', true),
  ('TECHNICIAN',       'Read-only access to assigned job cards.', true),
  ('INVENTORY MANAGER','Owns stock, products and transfers.', true),
  ('PURCHASE MANAGER', 'Owns supplier orders and goods receipt.', true),
  ('ACCOUNTANT',       'Bookkeeping, expenses and reports.', true),
  ('VIEWER',           'Read-only access to every module.', true)
on conflict (name) do nothing;

insert into public.permissions (module, action, description) values
('dashboard', 'view', 'dashboard.view'),
    ('showroom', 'view', 'showroom.view'),
    ('showroom', 'create', 'showroom.create'),
    ('showroom', 'edit', 'showroom.edit'),
    ('users', 'view', 'users.view'),
    ('users', 'create', 'users.create'),
    ('users', 'edit', 'users.edit'),
    ('users', 'delete', 'users.delete'),
    ('roles', 'view', 'roles.view'),
    ('roles', 'manage', 'roles.manage'),
    ('products', 'view', 'products.view'),
    ('products', 'create', 'products.create'),
    ('products', 'edit', 'products.edit'),
    ('products', 'delete', 'products.delete'),
    ('inventory', 'view', 'inventory.view'),
    ('inventory', 'create', 'inventory.create'),
    ('inventory', 'edit', 'inventory.edit'),
    ('inventory', 'transfer', 'inventory.transfer'),
    ('inventory', 'adjust', 'inventory.adjust'),
    ('inventory', 'reserve', 'inventory.reserve'),
    ('inventory', 'release', 'inventory.release'),
    ('inventory', 'delete', 'inventory.delete'),
    ('customers', 'view', 'customers.view'),
    ('customers', 'create', 'customers.create'),
    ('customers', 'edit', 'customers.edit'),
    ('customers', 'delete', 'customers.delete'),
    ('customers', 'export', 'customers.export'),
    ('sales', 'view', 'sales.view'),
    ('sales', 'create', 'sales.create'),
    ('sales', 'edit', 'sales.edit'),
    ('sales', 'cancel', 'sales.cancel'),
    ('sales', 'discount', 'sales.discount'),
    ('sales', 'approve', 'sales.approve'),
    ('billing', 'view', 'billing.view'),
    ('billing', 'create', 'billing.create'),
    ('billing', 'edit', 'billing.edit'),
    ('billing', 'cancel', 'billing.cancel'),
    ('billing', 'print', 'billing.print'),
    ('billing', 'export', 'billing.export'),
    ('payments', 'view', 'payments.view'),
    ('payments', 'create', 'payments.create'),
    ('payments', 'edit', 'payments.edit'),
    ('payments', 'cancel', 'payments.cancel'),
    ('finance', 'view', 'finance.view'),
    ('finance', 'create', 'finance.create'),
    ('finance', 'edit', 'finance.edit'),
    ('emi', 'view', 'emi.view'),
    ('emi', 'create', 'emi.create'),
    ('emi', 'edit', 'emi.edit'),
    ('emi', 'payment', 'emi.payment'),
    ('purchases', 'view', 'purchases.view'),
    ('purchases', 'create', 'purchases.create'),
    ('purchases', 'edit', 'purchases.edit'),
    ('purchases', 'delete', 'purchases.delete'),
    ('expenses', 'view', 'expenses.view'),
    ('expenses', 'create', 'expenses.create'),
    ('expenses', 'edit', 'expenses.edit'),
    ('expenses', 'approve', 'expenses.approve'),
    ('expenses', 'delete', 'expenses.delete'),
    ('accounting', 'view', 'accounting.view'),
    ('accounting', 'edit', 'accounting.edit'),
    ('accounting', 'create', 'accounting.create'),
    ('service', 'view', 'service.view'),
    ('service', 'create', 'service.create'),
    ('service', 'edit', 'service.edit'),
    ('service', 'complete', 'service.complete'),
    ('service', 'bill', 'service.bill'),
    ('service', 'discount', 'service.discount'),
    ('warranty', 'view', 'warranty.view'),
    ('warranty', 'create', 'warranty.create'),
    ('warranty', 'edit', 'warranty.edit'),
    ('insurance', 'view', 'insurance.view'),
    ('insurance', 'create', 'insurance.create'),
    ('insurance', 'edit', 'insurance.edit'),
    ('reminders', 'view', 'reminders.view'),
    ('reminders', 'create', 'reminders.create'),
    ('reminders', 'edit', 'reminders.edit'),
    ('notifications', 'view', 'notifications.view'),
    ('reports', 'view', 'reports.view'),
    ('reports', 'export', 'reports.export'),
    ('documents', 'view', 'documents.view'),
    ('documents', 'upload', 'documents.upload'),
    ('documents', 'delete', 'documents.delete'),
    ('audit', 'view', 'audit.view'),
    ('settings', 'view', 'settings.view'),
    ('settings', 'edit', 'settings.edit')
on conflict (module, action) do nothing;

-- Default matrix. '%' matches every module/action; SUPER ADMIN is implicit
-- (public.is_super_admin()) and therefore has no rows here.
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from (values
    -- ADMIN: everything
    ('ADMIN', '%', '%'),

    -- SHOWROOM MANAGER: operations, people and stock
    ('SHOWROOM MANAGER', 'dashboard', '%'),
    ('SHOWROOM MANAGER', 'users', 'view'),
    ('SHOWROOM MANAGER', 'showroom', 'view'),
    ('SHOWROOM MANAGER', 'products', '%'),
    ('SHOWROOM MANAGER', 'inventory', '%'),
    ('SHOWROOM MANAGER', 'customers', '%'),
    ('SHOWROOM MANAGER', 'sales', '%'),
    ('SHOWROOM MANAGER', 'billing', '%'),
    ('SHOWROOM MANAGER', 'payments', '%'),
    ('SHOWROOM MANAGER', 'finance', 'view'),
    ('SHOWROOM MANAGER', 'emi', '%'),
    ('SHOWROOM MANAGER', 'purchases', 'view'),
    ('SHOWROOM MANAGER', 'expenses', '%'),
    ('SHOWROOM MANAGER', 'accounting', 'view'),
    ('SHOWROOM MANAGER', 'service', '%'),
    ('SHOWROOM MANAGER', 'warranty', '%'),
    ('SHOWROOM MANAGER', 'insurance', '%'),
    ('SHOWROOM MANAGER', 'reminders', '%'),
    ('SHOWROOM MANAGER', 'notifications', '%'),
    ('SHOWROOM MANAGER', 'documents', '%'),
    ('SHOWROOM MANAGER', 'reports', '%'),
    ('SHOWROOM MANAGER', 'settings', 'view'),

    -- ACCOUNT MANAGER
    ('ACCOUNT MANAGER', 'dashboard', '%'),
    ('ACCOUNT MANAGER', 'accounting', '%'),
    ('ACCOUNT MANAGER', 'payments', '%'),
    ('ACCOUNT MANAGER', 'billing', '%'),
    ('ACCOUNT MANAGER', 'finance', '%'),
    ('ACCOUNT MANAGER', 'emi', '%'),
    ('ACCOUNT MANAGER', 'expenses', '%'),
    ('ACCOUNT MANAGER', 'sales', 'view'),
    ('ACCOUNT MANAGER', 'purchases', 'view'),
    ('ACCOUNT MANAGER', 'customers', 'view'),
    ('ACCOUNT MANAGER', 'reports', '%'),
    ('ACCOUNT MANAGER', 'documents', 'view'),
    ('ACCOUNT MANAGER', 'settings', 'view'),

    -- ACCOUNTANT
    ('ACCOUNTANT', 'dashboard', 'view'),
    ('ACCOUNTANT', 'accounting', 'view'),
    ('ACCOUNTANT', 'expenses', '%'),
    ('ACCOUNTANT', 'payments', 'view'),
    ('ACCOUNTANT', 'billing', 'view'),
    ('ACCOUNTANT', 'reports', '%'),
    ('ACCOUNTANT', 'settings', 'view'),

    -- SALES MANAGER
    ('SALES MANAGER', 'dashboard', '%'),
    ('SALES MANAGER', 'sales', '%'),
    ('SALES MANAGER', 'billing', '%'),
    ('SALES MANAGER', 'payments', '%'),
    ('SALES MANAGER', 'customers', '%'),
    ('SALES MANAGER', 'emi', '%'),
    ('SALES MANAGER', 'finance', 'view'),
    ('SALES MANAGER', 'products', 'view'),
    ('SALES MANAGER', 'inventory', 'view'),
    ('SALES MANAGER', 'reminders', '%'),
    ('SALES MANAGER', 'notifications', '%'),
    ('SALES MANAGER', 'documents', '%'),
    ('SALES MANAGER', 'reports', '%'),
    ('SALES MANAGER', 'settings', 'view'),

    -- SALES STAFF
    ('SALES STAFF', 'dashboard', 'view'),
    ('SALES STAFF', 'sales', 'view'),
    ('SALES STAFF', 'sales', 'create'),
    ('SALES STAFF', 'customers', 'view'),
    ('SALES STAFF', 'customers', 'create'),
    ('SALES STAFF', 'customers', 'edit'),
    ('SALES STAFF', 'payments', 'view'),
    ('SALES STAFF', 'payments', 'create'),
    ('SALES STAFF', 'billing', 'view'),
    ('SALES STAFF', 'inventory', 'view'),
    ('SALES STAFF', 'products', 'view'),
    ('SALES STAFF', 'emi', 'view'),
    ('SALES STAFF', 'reminders', 'view'),
    ('SALES STAFF', 'notifications', 'view'),
    ('SALES STAFF', 'settings', 'view'),

    -- SERVICE MANAGER
    ('SERVICE MANAGER', 'dashboard', '%'),
    ('SERVICE MANAGER', 'service', '%'),
    ('SERVICE MANAGER', 'warranty', '%'),
    ('SERVICE MANAGER', 'insurance', '%'),
    ('SERVICE MANAGER', 'customers', 'view'),
    ('SERVICE MANAGER', 'reminders', '%'),
    ('SERVICE MANAGER', 'notifications', '%'),
    ('SERVICE MANAGER', 'inventory', 'view'),
    ('SERVICE MANAGER', 'products', 'view'),
    ('SERVICE MANAGER', 'billing', 'view'),
    ('SERVICE MANAGER', 'payments', 'view'),
    ('SERVICE MANAGER', 'documents', '%'),
    ('SERVICE MANAGER', 'reports', '%'),
    ('SERVICE MANAGER', 'settings', 'view'),

    -- SERVICE ADVISOR
    ('SERVICE ADVISOR', 'dashboard', 'view'),
    ('SERVICE ADVISOR', 'service', 'view'),
    ('SERVICE ADVISOR', 'service', 'create'),
    ('SERVICE ADVISOR', 'service', 'complete'),
    ('SERVICE ADVISOR', 'customers', 'view'),
    ('SERVICE ADVISOR', 'warranty', 'view'),
    ('SERVICE ADVISOR', 'reminders', 'view'),
    ('SERVICE ADVISOR', 'notifications', 'view'),
    ('SERVICE ADVISOR', 'settings', 'view'),

    -- TECHNICIAN
    ('TECHNICIAN', 'service', 'view'),
    ('TECHNICIAN', 'notifications', 'view'),

    -- INVENTORY MANAGER
    ('INVENTORY MANAGER', 'dashboard', 'view'),
    ('INVENTORY MANAGER', 'inventory', '%'),
    ('INVENTORY MANAGER', 'products', '%'),
    ('INVENTORY MANAGER', 'purchases', 'view'),
    ('INVENTORY MANAGER', 'reports', '%'),
    ('INVENTORY MANAGER', 'documents', '%'),
    ('INVENTORY MANAGER', 'settings', 'view'),

    -- PURCHASE MANAGER
    ('PURCHASE MANAGER', 'dashboard', 'view'),
    ('PURCHASE MANAGER', 'purchases', '%'),
    ('PURCHASE MANAGER', 'products', 'view'),
    ('PURCHASE MANAGER', 'inventory', 'view'),
    ('PURCHASE MANAGER', 'inventory', 'create'),
    ('PURCHASE MANAGER', 'expenses', 'view'),
    ('PURCHASE MANAGER', 'reports', '%'),
    ('PURCHASE MANAGER', 'documents', '%'),
    ('PURCHASE MANAGER', 'settings', 'view'),

    -- VIEWER
    ('VIEWER', '%', 'view')
  ) as m(role_name, module, action)
  join public.roles r on r.name = m.role_name
  join public.permissions p
    on (m.module = '%' or p.module = m.module)
   and (m.action = '%' or p.action = m.action)
on conflict (role_id, permission_id) do nothing;
